server.port=${SERVER_APPLICATION_PORT}
spring.datasource.url=${POSTGRES_DB_URL_FOR_LOCAL_ENVIRONMENT}
spring.datasource.username=${POSTGRES_DB_USERNAME_FOR_LOCAL_ENVIRONMENT}
spring.datasource.password=${POSTGRES_DB_PASSWORD_FOR_LOCAL_ENVIRONMENT}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
spring.application.name=${SERVER_APPLICATION_NAME}